version: 1.0.{build}

image: Visual Studio 2017

init:
  - cmd: git config --global core.autocrlf true

clone_folder: c:\mill

environment:
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64
    JAVA_HOME: 'C:\Program Files\Java\jdk1.8.0'
  PATH: '%JAVA_HOME%\bin;C:\bin;C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%'

cache:
  - '%LOCALAPPDATA%\Coursier\cache'

install:
  - bash -lc "mkdir /c/bin && curl -Lo /c/bin/mill https://github.com/lihaoyi/mill/releases/download/0.1.4/0.1.4-12-f5250d"

build_script:
  - bash -lc "cd /c/mill && mill -i all main.test scalalib.test scalajslib.test"
