language: scala
sudo: required
dist: trusty

matrix:
  include:
  - stage: build
    env: CI_SCRIPT=ci/test-mill-release.sh
    jdk: oraclejdk8
  - stage: build
    env: CI_SCRIPT=ci/test-mill-release.sh
    jdk: oraclejdk9

  - stage: build
    env: CI_SCRIPT=ci/test-mill-dev.sh
    jdk: oraclejdk8
  - stage: build
    env: CI_SCRIPT=ci/test-mill-dev.sh
    jdk: oraclejdk9
  - stage: build
    env: CI_SCRIPT=ci/test-mill-bootstrap.sh
    jdk: oraclejdk9

  - stage: build
    env: CI_SCRIPT=ci/test-mill-0.sh
    jdk: oraclejdk8
  - stage: build
    env: CI_SCRIPT=ci/test-mill-1.sh
    jdk: oraclejdk8
  - stage: build
    env: CI_SCRIPT=ci/test-mill-2.sh
    jdk: oraclejdk8


  - stage: release
    env: CI_SCRIPT="ci/on-master.py ci/release.sh"
    jdk: oraclejdk8
  - stage: release
    env: CI_SCRIPT="ci/on-master.py ci/publish-docs.sh"
    jdk: oraclejdk8

script:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/0.1.7/0.1.7-86-e1da1b && chmod +x ~/bin/mill
  - export PATH=~/bin/mill:$PATH
  - "$CI_SCRIPT"

cache:
  directories:
  - $HOME/.coursier
