language: scala
sudo: required
dist: trusty

scala:
  - 2.12.4

jdk:
  - oraclejdk8

matrix:
  include:
  - stage: build
    env: CI_SCRIPT=ci/test-sbt.sh
  - stage: build
    env: CI_SCRIPT=ci/test-sbt-built.sh
  - stage: build
    env: CI_SCRIPT=ci/test-mill-built.sh
  - stage: build
    env: CI_SCRIPT=ci/test-mill-release.sh
#  - stage: release
#    env: CI_SCRIPT="ci/on-master.py ci/release.sh"
#  - stage: release
#    env: CI_SCRIPT="ci/on-master.py ci/publish-docs.sh"

script:
  - git fetch --unshallow --tags
  - "$CI_SCRIPT"
cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.coursier

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete