extends: [mill.javalib.JavaModule]

    mvnDeps = Seq(
    mvn"net.sourceforge.argparse4j:argparse4j:0.9.0",
    mvn"org.thymeleaf:thymeleaf:3.1.1.RELEASE"
    )
    
    def repositories = Seq("https://oss.sonatype.org/content/repositories/releases")
  }