extends: [mill.javalib.JavaModule]

# Add library dependencies that are visible to the compiler at compile-time but
# not visible at runtime. This is commonly used for "optional" dependencies that
# downstream users may or may not include depending on their needs
compileMvnDeps:
- javax.servlet:servlet-api:2.5
- org.eclipse.jetty:jetty-server:9.4.42.v20210604
- org.eclipse.jetty:jetty-servlet:9.4.42.v20210604

# Add library dependencies that are visible at runtime but not at compile-time.
runMvnDeps:
- javax.servlet:servlet-api:2.5
- org.eclipse.jetty:jetty-server:9.4.42.v20210604
- org.eclipse.jetty:jetty-servlet:9.4.42.v20210604

# Add additional Maven repositories to resolve dependencies from
repositories:
- https://oss.sonatype.org/content/repositories/releases

# Directly add jars on disk to your module classpath. Note that this does not
# resolve transitive dependencies of those jars, and so you need to ensure you
# include any transitive dependencies yourself
unmanagedClasspath:
- lib/nanojson-1.8.jar
