extends: [mill.javalib.JavaModule]
mvnDeps:
- org.thymeleaf:thymeleaf:3.1.1.RELEASE

# Add a custom maven repository URL
repositories: ["https://oss.sonatype.org/content/repositories/releases"]

# Set an explicit main class
mainClass: "foo.Foo2"

# Add an additional source folder and resource folder, in addition to the default one
sources: ["./src", "./custom-src"]
resources: ["./resources", "./custom-resources"]

# Configure java compiler and runtime options and env vars
javacOptions: [["-deprecation"]]
forkArgs: [["-Dmy.custom.property=my-prop-value"]]
forkEnv: { "MY_CUSTOM_ENV": "my-env-value" }