name: Publish Bridges

# Manually-triggered github action to publish mill-scala-compiler-bridges jars,
# since those do not change frequently enough to be worth including in the main
# publishing workflow that runs every Mill version
on:
  workflow_dispatch:
    inputs:
      bridge_versions:
        description: 'comma-separated list of Scala versions to publish or `all` for all supported versions'
        required: true
        type: string

jobs:
  publish-bridges:
    runs-on: ubuntu-latest

    concurrency: publish-sonatype-${{ github.sha }}

    env:
      MILL_STABLE_VERSION: 1
      MILL_SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      MILL_SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      MILL_PGP_SECRET_BASE64: ${{ secrets.SONATYPE_PGP_PRIVATE_KEY }}
      MILL_PGP_PASSPHRASE: ${{ secrets.SONATYPE_PGP_PRIVATE_KEY_PASSWORD }}
      LANG: "en_US.UTF-8"
      LC_MESSAGES: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      MILL_COMPILER_BRIDGE_VERSIONS: ${{ inputs.bridge_versions }}
    steps:
      - uses: actions/checkout@v5
        with: { fetch-depth: 0 }

      - run: ./mill -i mill.scalalib.PublishModule/ --publishArtifacts bridge.__.publishArtifacts


