name: Publish Bridges

# Manually-triggered github action to publish mill-scala-compiler-bridges jars,
# since those do not change frequently enough to be worth including in the main
# publishing workflow that runs every Mill version
on:
  workflow_dispatch:
    inputs:
      bridge_versions:
        description: 'comma-separated list of Scala versions to publish or `all` for all supported versions'
        required: true
        type: string

jobs:
  publish-bridges:
    runs-on: ubuntu-latest

    concurrency: publish-sonatype-${{ github.sha }}

    env:
      SONATYPE_PGP_SECRET: ${{ secrets.SONATYPE_PGP_SECRET }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_DEPLOY_USER }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_DEPLOY_PASSWORD }}
      SONATYPE_PGP_PASSWORD: ${{ secrets.SONATYPE_PGP_PASSWORD }}
      LANG: "en_US.UTF-8"
      LC_MESSAGES: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
      MILL_COMPILER_BRIDGE_VERSIONS: ${{ inputs.bridge_versions }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin

      - run:  ci/release-bridge-maven.sh
